Major change: merged GuiMods and GuiMods2
GuiMods was originally based on the simpler of two flow overview screens and GuiMods2 was based on the more complete Grid Parallel overview.

This new version of GuiMods now allows the user to select which flow oveview to use without reinstalling packages.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -13,31 +13,6 @@
 # The code also relies on a second request to backup an active file will not touch an existing backup
 
 qmlDir=/opt/victronenergy/gui/qml
-deviceListFile="$qmlDir/PageMain.qml"
-mainPagesFile="$qmlDir/main.qml"
-overviewMobileEnhancedFile="$qmlDir/OverviewMobileEnhanced.qml"
-reasonMessageFile="$qmlDir/SystemReasonMessage.qml"
-overviewAcValues="$qmlDir/OverviewAcValuesEnhanced.qml"
-objectAcConnection="$qmlDir/ObjectAcConnection.qml"
-overviewHubEnhanced="$qmlDir/OverviewHubEnhanced.qml"
-overviewSolarChargerFile="$qmlDir/OverviewSolarChargerEnhanced.qml"
-tileTankFile="$qmlDir/TileTankEnhanced.qml"
-powerGaugeFile="$qmlDir/PowerGauge.qml"
-powerGaugeBatteryFile="$qmlDir/PowerGaugeBattery.qml"
-multiFile="$qmlDir/MultiEnhanced.qml"
-inverterPopupFile="$qmlDir/InverterModePopUp.qml"
-acCurrentLimitPopUpFile="$qmlDir/AcCurrentLimitPopUp.qml"
-tileTempFile="$qmlDir/TileTemp.qml"
-hubDataFile="$qmlDir/HubData.qml"
-marqueeFile="$qmlDir/MarqueeEnhanced.qml"
-tileFile="$qmlDir/Tile.qml"
-relaySettingsFile="/opt/victronenergy/gui/qml/PageSettingsRelay.qml"
-relayOverviewFile="/opt/victronenergy/gui/qml/OverviewRelays.qml"
-relayTileFile="/opt/victronenergy/gui/qml/TileRelay.qml"
-
-settingsDisplayFile="$qmlDir/PageSettingsDisplay.qml"
-guiModsFile="$qmlDir/PageSettingsGuiMods.qml"
-gaugesFile="$qmlDir/PageSettingsGuiModsGauges.qml"
 
 #### following lines incorporate SetupHelper utilities into this script
 # Refer to the SetupHelper ReadMe file for details.
@@ -61,11 +36,27 @@ fi
 #### installing
 if [ $scriptAction == 'INSTALL' ] ; then
 
+    # insure the  GuiMods2 is uninstalled since they can't coexist
+    if [ -f "$installedFlagPrefix""GuiMods2" ]; then
+        logMessage "uninstalling the original GuiMods2 - can't coexist with GuiMods"
+        "/data/GuiMods2/setup" "uninstall" "deferReboot"
+        if (( $? == $exitReboot )); then
+            rebootNeeded=true
+        fi
+        activateGridParallelOverview=true
+    else
+        activateGridParallelOverview=false
+    fi
+
+    # cleanup from previous verisons
+    restoreActiveFile "$qmlDir/DetailCriticalOutput.qml"
+    restoreActiveFile "$qmlDir/DetailNoncriticalOutput.qml"
+
     # create dbus Settings if they haven't been set previously
     # if one setting exists, assume they are all there
     # NOTE: if new settings are added in the future, change test for that one
     # to avoid creating that new parameter !!!!
-    dbus-send --system --print-reply=literal --dest=com.victronenergy.settings /Settings/GuiMods/GaugeLimits/BatteryMaxChargeCurrent\
+    dbus-send --system --print-reply=literal --dest=com.victronenergy.settings /Settings/GuiMods/UseEnhancedGridParallelFlowOverview\
                 com.victronenergy.BusItem.GetValue &> /dev/null
     if (( $? != 0 )); then
         logMessage "creating GuiMods Settings"
@@ -86,6 +77,8 @@ if [ $scriptAction == 'INSTALL' ] ; then
             {"path":"/GuiMods/UseEnhancedFlowOverview", "default":1, "min":0, "max":1},\
             {"path":"/GuiMods/ShowEnhancedFlowOverviewTanks", "default":1, "min":0, "max":1},\
             {"path":"/GuiMods/ShowEnhancedFlowOverviewTemps", "default":1, "min":0, "max":1},\
+            {"path":"/GuiMods/ShowEnhancedFlowLoadsOnInput", "default":1, "min":0, "max":1},\
+            {"path":"/GuiMods/EnhancedFlowCombineLoads", "default":0, "min":0, "max":1},\
             {"path":"/GuiMods/ShowGauges", "default":1, "min":0, "max":1},\
             {"path":"/GuiMods/ShowTileOverview", "default":1, "min":0, "max":1},\
             {"path":"/GuiMods/MoveSettings", "default":1, "min":0, "max":1},\
@@ -103,7 +96,16 @@ if [ $scriptAction == 'INSTALL' ] ; then
             {"path": "/Relay/5/CustomName", "default":""},\
             {"path": "/Relay/5/Show", "default":1, "min":0, "max":1}, \
             {"path":"/GuiMods/ShowRelayOverview", "default":1, "min":0, "max":1}, \
-            {"path":"/GuiMods/GaugeLimits/BatteryMaxChargeCurrent", "default":0.0} ]' > /dev/null
+            {"path":"/GuiMods/GaugeLimits/BatteryMaxChargeCurrent", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/AcOutputNonCriticalMaxPower", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/PvOnGridMaxPower", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/PvOnOutputMaxPower", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/MaxChargerPower", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/MaxFeedInPower", "default":0.0}, \
+            {"path":"/GuiMods/ShowInactiveFlowTiles", "default":1, "min":0, "max":2}, \
+            {"path":"/GuiMods/GaugeLimits/DcSystemMaxLoad", "default":0.0}, \
+            {"path":"/GuiMods/GaugeLimits/DcSystemMaxCharge", "default":0.0}, \
+            {"path":"/GuiMods/UseEnhancedGridParallelFlowOverview", "default":0, "min":0, "max":1} ]' > /dev/null
     fi
 
     # move setup options to Settings
@@ -112,7 +114,7 @@ if [ $scriptAction == 'INSTALL' ] ; then
                 || [ -f "$setupOptionsDir/moveSettings" ] \
                 || [ -f "$setupOptionsDir/hideTileOverview" ] \
                 || [ -f "$setupOptionsDir/enhancedFlow" ]; then
-            logMessage "moving setup options to GuiMods Settings"
+            logMessage "moving setup options to GuiMods2 Settings"
             
             if [ -f "$setupOptionsDir/useEnhancedOverview" ]; then
                 setSetting 1 /Settings/GuiMods/UseEnhancedMobileOverview
@@ -175,53 +177,69 @@ if [ $scriptAction == 'INSTALL' ] ; then
             rm -f "$setupOptionsDir/acCurrentLimitPresets"
 
              # remove old Settings
-            dbus -y com.victronenergy.settings /Settings RemoveSettings\
-                    '%["InverterLimits/PeakPower", "InverterLimits/ContiuousPower",\
-                    "InverterLimits/CautionPower", "InverterLimits/OutputPowerLimit",\
-                    "SystemSetup/MaxDischargeCurrent",\
-                    "InverterLimits/AcCurrentLimit/Preset1", "InverterLimits/AcCurrentLimit/Preset2",\
-                    "InverterLimits/AcCurrentLimit/Preset3", "InverterLimits/AcCurrentLimit/Preset4",\
-                    "PvCharger/MaxPower" ]' > /dev/null
+            removeDbusSettings  "InverterLimits/PeakPower", "InverterLimits/ContiuousPower",\
+                                "InverterLimits/CautionPower", "InverterLimits/OutputPowerLimit",\
+                                "SystemSetup/MaxDischargeCurrent",\
+                                "InverterLimits/AcCurrentLimit/Preset1", "InverterLimits/AcCurrentLimit/Preset2",\
+                                "InverterLimits/AcCurrentLimit/Preset3", "InverterLimits/AcCurrentLimit/Preset4",\
+                                "PvCharger/MaxPower"
 
         fi
     fi
-
-    # clean up from previous versions
-    restoreActiveFile "$qmlDir/OverviewHub"
-    restoreActiveFile "$qmlDir/OverviewAcValues.qml"
-    restoreActiveFile "$qmlDir/OverviewSolarCharger.qml"
-    restoreActiveFile "$qmlDir/TileTank.qml"
-    restoreActiveFile "$qmlDir/Multi.qml"
-    restoreActiveFile "$qmlDir/Marquee.qml"
     
-    logMessage "installing $packageName files"
-    updateActiveFile "$deviceListFile"
-    updateActiveFile "$mainPagesFile"
-    updateActiveFile "$overviewMobileEnhancedFile"
-    updateActiveFile "$reasonMessageFile"
-    updateActiveFile "$overviewAcValues"
-    updateActiveFile "$objectAcConnection"
-    updateActiveFile "$overviewHubEnhanced"
-    updateActiveFile "$hubDataFile"
-    updateActiveFile "$overviewSolarChargerFile"
-    updateActiveFile "$powerGaugeFile"
-    updateActiveFile "$powerGaugeBatteryFile"
-    updateActiveFile "$multiFile"
-    updateActiveFile "$inverterPopupFile"
-    updateActiveFile "$acCurrentLimitPopUpFile"
-    updateActiveFile "$tileTankFile"
-    updateActiveFile "$tileTempFile"
-    updateActiveFile "$settingsDisplayFile"
-    updateActiveFile "$guiModsFile"
-    updateActiveFile "$gaugesFile"
-    updateActiveFile "$marqueeFile"
-    updateActiveFile "$tileFile"
-    updateActiveFile "$relaySettingsFile"
-    updateActiveFile "$relayOverviewFile"
-    updateActiveFile "$relayTileFile"
+    # GuiMods2 was just uninstalled, so switch to the grid parallel overview so user sees same screen as with GuiMods2
+    if $activateGridParallelOverview ; then
+        logMessage "GuiMods is replacing GuiMods2 - enable grid paraellel overview in GuiMods"
+        setSetting 1 "/Settings/GuiMods/UseEnhancedGridParallelFlowOverview"
+    fi
+    
+    # remove GuiMods2 from packageList - if it's reistalled, it will ba added back
+    # but we want to skip any checks for GuiMods including from packageInstaller
+    if [ $(grep -c "GuiMods2" "$packageListFile") != 0 ]; then
+        logMessage "removing GuiMods2 from packageList"
+        sed -i -e /GuiMods2/d "$packageListFile"
+    fi
 
-    # clean up from previous versions
-    restoreActiveFile "$versionsFile"
+    logMessage "installing $packageName files"
+    updateActiveFile "$qmlDir/PageMain.qml"
+    updateActiveFile "$qmlDir/main.qml"
+    updateActiveFile "$qmlDir/OverviewMobileEnhanced.qml"
+    updateActiveFile "$qmlDir/SystemReasonMessage.qml"
+    updateActiveFile "$qmlDir/OverviewAcValuesEnhanced.qml"
+    updateActiveFile "$qmlDir/OverviewAcValuesEnhancedGP.qml"
+    updateActiveFile "$qmlDir/ObjectAcConnection.qml"
+    updateActiveFile "$qmlDir/OverviewHubEnhanced.qml"
+    updateActiveFile "$qmlDir/OverviewGridParallelEnhanced.qml"
+    updateActiveFile "$qmlDir/HubData.qml"
+    updateActiveFile "$qmlDir/OverviewSolarChargerEnhanced.qml"
+    updateActiveFile "$qmlDir/OverviewSolarInverter.qml"
+    updateActiveFile "$qmlDir/PowerGauge.qml"
+    updateActiveFile "$qmlDir/PowerGaugeMulti.qml"
+    updateActiveFile "$qmlDir/PowerGaugeBattery.qml"
+    updateActiveFile "$qmlDir/MultiEnhanced.qml"
+    updateActiveFile "$qmlDir/MultiEnhancedGP.qml"
+    updateActiveFile "$qmlDir/TileTankEnhanced.qml"
+    updateActiveFile "$qmlDir/TileTemp.qml"
+    updateActiveFile "$qmlDir/PageSettingsDisplay.qml"
+    updateActiveFile "$qmlDir/PageSettingsGuiMods.qml"
+    updateActiveFile "$qmlDir/PageSettingsGuiModsGauges.qml"
+    updateActiveFile "$qmlDir/MarqueeEnhanced.qml"
+    updateActiveFile "$qmlDir/Tile.qml"
+    updateActiveFile "$qmlDir/PageSettingsRelay.qml"
+    updateActiveFile "$qmlDir/OverviewRelays.qml"
+    updateActiveFile "$qmlDir/TileRelay.qml"
+    updateActiveFile "$qmlDir/DetailInverter.qml"
+    updateActiveFile "$qmlDir/DetailAcInput.qml"
+    updateActiveFile "$qmlDir/DetailBattery.qml"
+    updateActiveFile "$qmlDir/DetailLoadsOnOutput.qml"
+    updateActiveFile "$qmlDir/DetailLoadsOnInput.qml"
+    updateActiveFile "$qmlDir/DetailPvCharger.qml"
+    updateActiveFile "$qmlDir/PvChargerRow.qml"
+    updateActiveFile "$qmlDir/DetailPvInverter.qml"
+    updateActiveFile "$qmlDir/PvInverterRow.qml"
+    
+    # cleanup from older versions
+    restoreActiveFile "$qmlDir/PageSettingsGuiModsVersions.qml"
 
     logMessage "++ $packageName installed"
 fi
@@ -230,39 +248,44 @@ fi
 # uninstalling - check scriptAction again
 # if an install step failed package needs to be removed
 if [ $scriptAction == 'UNINSTALL' ] ; then
-    restoreActiveFile "$deviceListFile"
-    restoreActiveFile "$mainPagesFile"
-    restoreActiveFile "$overviewMobileEnhancedFile"
-    restoreActiveFile "$reasonMessageFile"
-    restoreActiveFile "$overviewAcValues"
-    restoreActiveFile "$objectAcConnection"
-    restoreActiveFile "$overviewHubEnhanced"
-    restoreActiveFile "$hubDataFile"
-    restoreActiveFile "$overviewSolarChargerFile"
-    restoreActiveFile "$tileTankFile"
-    restoreActiveFile "$tileTempFile"
-    restoreActiveFile "$powerGaugeFile"
-    restoreActiveFile "$powerGaugeBatteryFile"
-    restoreActiveFile "$multiFile"
-    restoreActiveFile "$inverterPopupFile"
-    restoreActiveFile "$acCurrentLimitPopUpFile"
-    restoreActiveFile "$settingsDisplayFile"
-    restoreActiveFile "$guiModsFile"
-    restoreActiveFile "$gaugesFile"
-    restoreActiveFile "$marqueeFile"
-    restoreActiveFile "$tileFile"
-    restoreActiveFile "$relaySettingsFile"
-    restoreActiveFile "$relayOverviewFile"
-    restoreActiveFile "$relayTileFile"
+    restoreActiveFile "$qmlDir/PageMain.qml"
+    restoreActiveFile "$qmlDir/main.qml"
+    restoreActiveFile "$qmlDir/OverviewMobileEnhanced.qml"
+    restoreActiveFile "$qmlDir/SystemReasonMessage.qml"
+    restoreActiveFile "$qmlDir/OverviewAcValuesEnhanced.qml"
+    restoreActiveFile "$qmlDir/OverviewAcValuesEnhancedGP.qml"
+    restoreActiveFile "$qmlDir/ObjectAcConnection.qml"
+    restoreActiveFile "$qmlDir/OverviewGridParallelEnhanced.qml"
+    restoreActiveFile "$qmlDir/HubData.qml"
+    restoreActiveFile "$qmlDir/OverviewSolarChargerEnhanced.qml"
+    restoreActiveFile "$qmlDir/OverviewSolarInverter.qml"
+    restoreActiveFile "$qmlDir/TileTankEnhanced.qml"
+    restoreActiveFile "$qmlDir/TileTemp.qml"
+    restoreActiveFile "$qmlDir/PageSettingsDisplay.qml"
+    restoreActiveFile "$qmlDir/PowerGauge.qml"
+    restoreActiveFile "$qmlDir/PowerGaugeMulti.qml"
+    restoreActiveFile "$qmlDir/PowerGaugeBattery.qml"
+    restoreActiveFile "$qmlDir/MultiEnhanced.qml"
+    restoreActiveFile "$qmlDir/MultiEnhancedGP.qml"
+    restoreActiveFile "$qmlDir/PageSettingsGuiMods.qml"
+    restoreActiveFile "$qmlDir/PageSettingsGuiModsGauges.qml"
+    restoreActiveFile "$qmlDir/MarqueeEnhanced.qml"
+    restoreActiveFile "$qmlDir/Tile.qml"
+    restoreActiveFile "$qmlDir/PageSettingsRelay.qml"
+    restoreActiveFile "$qmlDir/OverviewRelays.qml"
+    restoreActiveFile "$qmlDir/TileRelay.qml"
+    restoreActiveFile "$qmlDir/DetailInverter.qml"
+    restoreActiveFile "$qmlDir/DetailAcInput.qml"
+    restoreActiveFile "$qmlDir/DetailBattery.qml"
+    restoreActiveFile "$qmlDir/DetailLoadsOnOutput.qml"
+    restoreActiveFile "$qmlDir/DetailLoadsOnInput.qml"
+    restoreActiveFile "$qmlDir/DetailPvCharger.qml"
+    restoreActiveFile "$qmlDir/PvChargerRow.qml"
+    restoreActiveFile "$qmlDir/DetailPvInverter.qml"
+    restoreActiveFile "$qmlDir/PvInverterRow.qml"
 
-    # clean up from previous versions
-    restoreActiveFile "$qmlDir/OverviewHub"
-    restoreActiveFile "$qmlDir/OverviewAcValues.qml"
-    restoreActiveFile "$qmlDir/OverviewSolarCharger.qml"
-    restoreActiveFile "$qmlDir/TileTank.qml"
-    restoreActiveFile "$qmlDir/Multi.qml"
-    restoreActiveFile "$qmlDir/Marquee.qml"
-    restoreActiveFile "$versionsFile"
+    # cleanup from older versions
+    restoreActiveFile "$qmlDir/PageSettingsGuiModsVersions.qml"
 
     logMessage "++ $packageName uninstalled"
 fi
